pet_controllers:
    resource: '../src/Pet/Controller/'
    type: attribute
    prefix: /pet

card_controllers:
    resource: '../src/MedCard/Controller/'
    type: attribute
    prefix: /card

site_controllers:
    resource: '../src/Site/Controller/'
    type: attribute
    prefix: /
