services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - DATABASE_URL=postgresql://app_user:app_password@db:5432/app_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

volumes:
  postgres_data: